apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: demo-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-055faf27da4e15c26
  directoryPerms: "700"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: demo-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-demo
  template:
    metadata:
      labels:
        app: web-demo
    spec:
      containers:
        - name: web-app
          image:  mahmoudabdelatif/app:vc
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data-volume
              mountPath: /data

      volumes:
        - name: data-volume
          persistentVolumeClaim: 
            claimName: pvc-1
            

---


