node {
    git branch: 'main', url: 'https://github.com/0elshenawy/DevOps-Cloud.git'

    stage('Build') {
        try {
            sh 'echo "building stage"'
        } catch (Exception e) {
            sh 'echo "exception found in build stage"'
            throw e
        }
    }

    stage('Test') {
        if (env.BRANCH_NAME == 'feature') {
            sh 'echo "testing stage"'
        } else {
            sh 'echo "skipping testing stage"'
        }
    }
}
